theme: jekyll-theme-minimal
title: Sona Mansuryan
description: AI/ML Engineer | Deep Learning & Reinforcement Learning Enthusiast
remote_theme: pages-themes/minimal@v0.2.0

social_links:
  linkedin: sona-mansuryan
  github: sonamansuryan
  email: mansuryansona04@gmail.com
